### ISSUE TITLE
SqlException: Violation of PRIMARY KEY constraint 'PK_Event'

### ISSUE THREAD

**Issue by cameronfletcher** [dddlib/dddlib#134]
I saw this happen on the [build server](http://teamcity.cameronfletcher.com/viewLog.html?buildId=836&tab=buildResultsDiv&buildTypeId=dddlib_Dddlib), think it needs some investigation...

```
[src\dddlib.msbuild.teamcity] PerformanceTest (1m:41s)
[00:49:27][PerformanceTest] Exec (1m:41s)
[00:49:27][Exec] perftest.exe
[00:49:27][Exec] Running...
[00:50:38][Exec] 
[00:50:38][Exec] Unhandled Exception: System.Data.SqlClient.SqlException: Violation of PRIMARY KEY constraint 'PK_Event'. Cannot insert duplicate key in object 'dddlib.Events'. The duplicate key value is (65).
[00:50:38][Exec]    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
[00:50:38][Exec]    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
[00:50:38][Exec]    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
[00:50:38][Exec]    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
[00:50:38][Exec]    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
[00:50:38][Exec]    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
[00:50:38][Exec]    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
[00:50:38][Exec]    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
[00:50:38][Exec]    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
[00:50:38][Exec]    at dddlib.Persistence.SqlServer.SqlServerEventStore.CommitStream(Guid streamId, IEnumerable`1 events, Guid correlationId, String preCommitState, String& postCommitState) in C:\TeamCity\buildAgent\work\f69da751c649bdca\src\dddlib.Persistence\SqlServer\SqlServerEventStore.cs:line 220
[00:50:38][Exec]    at dddlib.Persistence.Sdk.EventStoreRepository.SaveInternal[T](T aggregateRoot, Guid correlationId) in C:\TeamCity\buildAgent\work\f69da751c649bdca\src\dddlib.Persistence\Sdk\EventStoreRepository.cs:line 140
[00:50:38][Exec]    at dddlib.Persistence.Sdk.EventStoreRepository.Save[T](T aggregateRoot, Guid correlationId) in C:\TeamCity\buildAgent\work\f69da751c649bdca\src\dddlib.Persistence\Sdk\EventStoreRepository.cs:line 63
[00:50:38][Exec]    at dddlib.Persistence.Sdk.EventStoreRepository.Save[T](T aggregateRoot) in C:\TeamCity\buildAgent\work\f69da751c649bdca\src\dddlib.Persistence\Sdk\EventStoreRepository.cs:line 48
[00:50:38][Exec]    at perftest.Program.ExecuteSqlServerEventStoreTest(Int32 iteration) in C:\TeamCity\buildAgent\work\f69da751c649bdca\src\tests\perftest\Program.cs:line 147
[00:50:38][Exec]    at perftest.Program.<>c__DisplayClass0.<RunForContinuousIntegration>b__3() in C:\TeamCity\buildAgent\work\f69da751c649bdca\src\tests\perftest\Program.cs:line 92
[00:50:38][Exec]    at HdrHistogram.HistogramExtensions.RecordLatency(HistogramBase histogram, Action action)
[00:50:38][Exec]    at perftest.Program.RunForContinuousIntegration() in C:\TeamCity\buildAgent\work\f69da751c649bdca\src\tests\perftest\Program.cs:line 92
[00:50:38][Exec]    at perftest.Program.Main(String[] args) in C:\TeamCity\buildAgent\work\f69da751c649bdca\src\tests\perftest\Program.cs:line 56
[00:51:08][Exec] C:\TeamCity\buildAgent\work\f69da751c649bdca\src\dddlib.msbuild(89, 5): error MSB3073: The command "perftest.exe" exited with code 255.
[00:51:09][Step 2/2] Process exited with code 1
```

**Comment by cameronfletcher** [comment]
So... https://support.microsoft.com/en-us/kb/3011465

**Comment by cameronfletcher** [comment]
I've only seen this manifest in the performance tests.
